version: "3.9"

services:
  web:
    image: nginx:latest
    container_name: web
    networks:
      - backend
      - moodle_net
    ports:
      - "0.0.0.0:8080:80" # [HOST_IP_BIND:]HOST_PORT:CONTAINER_PORT
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/public:/usr/share/nginx/html
    env_file:
      - ./config/config.env
    command: ["nginx-debug", "-g", "daemon off;"]
    depends_on:
      - moodle
      - petclinic
    restart: unless-stopped

  moodle-db:
    image: mariadb:10.6
    container_name: moodle-db
    restart: unless-stopped
    networks:
      - moodle_net
    env_file:
      - ./config/config.env
    volumes:
      - moodle_db_data:/var/lib/mysql

  moodle:
    image: brandkern/moodle:4.5-latest
    container_name: moodle
    restart: unless-stopped
    networks:
      - moodle_net
    env_file:
      - ./config/config.env
    volumes:
      - moodle_data:/var/www/moodledata
      - ./apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - moodle-db

  petclinic-db:
    image: postgres:15-alpine
    container_name: petclinic-db
    restart: unless-stopped
    networks:
      - backend
    env_file:
      - ./config/config.env
    volumes:
      - petclinic_db_data:/var/lib/postgresql/data

  petclinic:
    build:
      context: ./spring-petclinic
      dockerfile: Dockerfile
    image: local/petclinic:latest
    container_name: petclinic
    restart: unless-stopped
    networks:
      - backend
    env_file:
      - ./config/config.env
    depends_on:
      - petclinic-db

networks:
  backend:
    driver: bridge
  moodle_net:
    driver: bridge

volumes:
  moodle_db_data:
  moodle_data:
  petclinic_db_data:
