version: "3.9"

services:
  web:
    image: nginx:latest
    container_name: web
    networks:
      - backend
      - moodle_net
    ports:
      - "0.0.0.0:8080:80" # [HOST_IP_BIND:]HOST_PORT:CONTAINER_PORT
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    env_file:
      - ./config/nginx.env
    command: ["nginx-debug", "-g", "daemon off;"]
    depends_on:
      - moodle
    restart: unless-stopped

  moodle-db:
    image: mariadb:10.6
    container_name: moodle-db
    restart: always
    networks:
      - moodle_net
    env_file:
      - ./config/moodle-db.env
    volumes:
      - moodle_db_data:/var/lib/mysql

  moodle:
    image: brandkern/moodle:4.5-latest
    container_name: moodle
    restart: always
    networks:
      - moodle_net
    env_file:
      - ./config/moodle.env
    volumes:
      - moodle_data:/var/www/moodledata
      - ./apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - moodle-db

networks:
  backend:
    driver: bridge
  moodle_net:
    driver: bridge

volumes:
  moodle_db_data:
  moodle_data:
